- DVSAdmin.BusinessLogic/DVSAdmin.BusinessLogic.csproj
- DVSAdmin.BusinessLogic/Models/RegisterDashboard/DIPDto.cs
- DVSAdmin.BusinessLogic/Services/RegisterDashboard/IRegisterDashboardService.cs
- DVSAdmin.BusinessLogic/Services/RegisterDashboard/RegisterDashboardService.cs
- DVSAdmin.CommonUtility/AWS/ISecretManager.cs
- DVSAdmin.CommonUtility/AWS/SecretManager.cs
- DVSAdmin.CommonUtility/Constants.cs
- DVSAdmin.CommonUtility/DVSAdmin.CommonUtility.csproj
- DVSAdmin.CommonUtility/Helper.cs
- DVSAdmin.Data/DVSAdmin.Data.csproj
- DVSAdmin.Data/DVSAdminDbContext.cs
- DVSAdmin.Data/GenericRepository.cs
- DVSAdmin.Data/IGenericRepository.cs
- DVSAdmin.UnitTests/BusinessLogic/RegisterDashboard/RegisterDashboardTests.cs
- DVSAdmin.UnitTests/DVSAdmin.UnitTests.csproj
- DVSAdmin.UnitTests/DVSAdmin/HomeControllerTests.cs
- DVSAdmin.UnitTests/GlobalUsings.cs
- DVSAdmin.sln
- DVSAdmin/DVSAdmin.csproj
- DVSAdmin/appsettings.Dev.json
- DVSAdmin/appsettings.Development.json
- DVSAdmin/appsettings.Prod.json
- DVSAdmin/appsettings.Staging.json
* Add Business Logic Layer - folder structure ,sample classes and interface (DVSAdmin.BusinessLogic)
* Add Data Access Layer - folder structure and sample classes and interface (DVSAdmin.Data)
* Add Unit Tests - folder structure and sample unit test classes (DVSAdmin.UnitTests)
* Add Common Utility - folder structure Sample static helper class, interfaces (DVSAdmin.CommonUtility)
> Create Project Structure

- .dockerignore
- Dockerfile
Adds a `Dockerfile` and `.dockerignore`  to containerize the repo and dockerize the repo.
User Story - https://dev.azure.com/BEIS-DevOps/DVS%20Register/_workitems/edit/29326
> feat(docker): Add Dockerfile

- DVSAdmin/Views/PreRegistrationReview/PreRegAtAGlance.cshtml
- DVSAdmin/Views/Shared/_Layout.cshtml
- package-lock.json
> OfDIA review portal page

- DVSAdmin/Views/CertificateReview/CertificateReview.cshtml
- DVSAdmin/Views/CertificateReview/CertificateValidation.cshtml
- Move H1 into the grid
- Update all headings to correct heading structure
> OfDIA Certificate Review page heading changes

- DVSAdmin/Controllers/CertificateReviewController.cs
- DVSAdmin/Views/CertificateReview/ApproveSubmission.cshtml
- DVSAdmin/Views/CertificateReview/ConfirmApproval.cshtml
Bug fixes
- 32031
- 32032
- 32033
> fix(navigation): navigation fixes in approve submission page

- DVSAdmin.BusinessLogic/Automapper/AutomapperProfile.cs
- DVSAdmin.BusinessLogic/Models/CertificateInformationDto.cs
- DVSAdmin.BusinessLogic/Models/CertificateReviewDto.cs
- DVSAdmin.BusinessLogic/Models/ProviderDto.cs
- DVSAdmin.BusinessLogic/Services/CertificateReviewService.cs
- DVSAdmin.CommonUtility/Models/Enums/ProviderStatusEnum.cs
- DVSAdmin.Data/Entities/CertificateInformation.cs
- DVSAdmin.Data/Entities/CertificateReview.cs
- DVSAdmin.Data/Entities/Provider.cs
- DVSAdmin.Data/Repositories/CertificateReviewRepository.cs
- DVSAdmin/Controllers/CertificateReviewController.cs
- DVSAdmin/Views/CertificateReview/ApproveSubmission.cshtml
- DVSAdmin/Views/CertificateReview/CertificateReview.cshtml
- DVSAdmin/Views/CertificateReview/CertificateValidation.cshtml
- DVSAdmin/Views/CertificateReview/PartialViews/_ArchiveView.cshtml
- DVSAdmin/Views/CertificateReview/PartialViews/_CertificateDetailsView.cshtml
- DVSAdmin/Views/CertificateReview/PartialViews/_CertificateReviewsView.cshtml
- DVSAdmin/Views/CertificateReview/PartialViews/_ContactView.cshtml
- DVSAdmin/Views/CertificateReview/PartialViews/_ServiceDetailsView.cshtml
- DVSAdmin/Views/CertificateReview/RejectSubmission.cshtml
> Certificate information table splited - code changes

- DVSAdmin.BusinessLogic/Models/CertificateReview/CertificateInformationDto.cs
- DVSAdmin.BusinessLogic/Services/RegManagement/IRegManagementService.cs
- DVSAdmin.BusinessLogic/Services/RegManagement/RegManagementService.cs
- DVSAdmin.CommonUtility/Models/Enums/ProviderStatusEnum.cs
- DVSAdmin.Data/Repositories/CertificateReview/CertificateReviewRepository.cs
- DVSAdmin/Controllers/RegisterManagementController.cs
- DVSAdmin/Extensions/HtmlExtensions.cs
- DVSAdmin/Models/RegManagement/ProviderDetailsViewModel.cs
- DVSAdmin/Models/RegManagement/ServiceDetailsViewModel.cs
- DVSAdmin/Views/RegisterManagement/PartialViews/_ServiceDetailsView.cshtml
- DVSAdmin/Views/RegisterManagement/ProviderDetails.cshtml
- DVSAdmin/Views/RegisterManagement/PublishService.cshtml
- DVSAdmin/Views/RegisterManagement/ServiceDetails.cshtml
- DVSAdmin/appsettings.json
> feat(register-management): provider details and service details screens integration

- DVSAdmin.BusinessLogic/Services/RegManagement/RegManagementService.cs
- DVSAdmin.Data/DVSAdminDbContext.cs
- DVSAdmin.Data/Entities/RegisterPublishLog.cs
- DVSAdmin.Data/Repositories/RegisterManagement/IRegManagementRepository.cs
- DVSAdmin.Data/Repositories/RegisterManagement/RegManagementRepository.cs
> feat(register-management): log published details

- DVSAdmin/Views/CertificateReview/CertificateValidation.cshtml
- DVSAdmin/package-lock.json
- DVSAdmin/package.json
> fix(package.json): fix for parse error

- DVSAdmin/Views/CertificateReview/ApprovalConfirmation.cshtml
- DVSAdmin/Views/CertificateReview/ApproveSubmission.cshtml
- DVSAdmin/Views/CertificateReview/ConfirmApproval.cshtml
Added the 3 screens for Approve Submission.
> feat(certificate-review):Approvalscreens

- DVSAdmin/Views/CertificateReview/ConfirmRejection.cshtml
- DVSAdmin/Views/CertificateReview/RejectSubmission.cshtml
- DVSAdmin/Views/CertificateReview/RejectionConfirmation.cshtml
> feat(certificate-review):RejectionScreensDesign

- DVSAdmin.BusinessLogic/Services/PublicInterestCheck/IPublicInterestCheckService.cs
- DVSAdmin.BusinessLogic/Services/PublicInterestCheck/PublicInterestService.cs
- DVSAdmin.CommonUtility/Models/Enums/PublicInterestCheckEnum.cs
- DVSAdmin.Data/DVSAdmin.Data.csproj
- DVSAdmin.Data/Entities/ProviderProfile.cs
- DVSAdmin.Data/Entities/PublicInterestCheck.cs
- DVSAdmin.Data/Entities/Service.cs
- DVSAdmin.Data/Repositories/PublicInterestCheck/IPublicInterestCheckRepository.cs
- DVSAdmin.Data/Repositories/PublicInterestCheck/PublicInterestCheckRepository.cs
- DVSAdmin/Startup.cs
> feat(db-change) : entity , repository and service for public interest check

- DVSAdmin/Views/PublicInterestSecondaryCheck/PublicInterestApproveSecondaryCheck.cshtml
- DVSAdmin/Views/PublicInterestSecondaryCheck/PublicInterestCheckApproved.cshtml
- DVSAdmin/Views/PublicInterestSecondaryCheck/PublicInterestCheckConfirmApproval.cshtml
Added the screens for PI check secondary review.
> feat(public-interest-check):design for PI check second reviewer screens.

- DVSAdmin.CommonUtility/DVSAdmin.CommonUtility.csproj
- DVSAdmin.Data/DVSAdmin.Data.csproj
- DVSAdmin.UnitTests/DVSAdmin.UnitTests.csproj
- DVSAdmin/DVSAdmin.csproj
- DVSAdmin/package-lock.json
Added some packages explicitly to patch vulnerable versions of implicitly used packages.
> fix(common-utility): update packages

- DVSAdmin/Middleware/SecurityHeadersMiddleware.cs
Implementation of the strict CSP headers on Admin.
> feat(dvs-45-admin):Implementation of the strict CSP headers on Admin.

- DVSAdmin/Views/Consent/Consent.cshtml
- DVSAdmin/Views/Consent/ConsentSuccess.cshtml
- DVSAdmin/Views/Consent/ProceedApplicationConsent.cshtml
- DVSAdmin/Views/Consent/ProceedApplicationConsentError.cshtml
- DVSAdmin/Views/Consent/ProceedApplicationConsentSuccess.cshtml
- DVSAdmin/Views/Shared/_Layout.cshtml
- DVSAdmin/Views/Shared/_LayoutConsent.cshtml
- DVSAdmin/Views/Shared/_LayoutLoggedIn.cshtml
@AiswaryaBEIS this will need a pull and local test - i'll message
> Add privacy and accessibility statement links to footer

- DVSAdmin.Data/Repositories/CertificateReview/CertificateReviewRepository.cs
rejection reasons should be cleared while approval only
> fix(restore) : fix for rejection reason getting cleared on save as draft click

- DVSAdmin.BusinessLogic/DVSAdmin.BusinessLogic.csproj
- DVSAdmin.BusinessLogic/Services/BackgroundJobs/BackgroundJobService.cs
- DVSAdmin.BusinessLogic/Services/BackgroundJobs/IBackgroundJobService.cs
- DVSAdmin.Data/Repositories/BackgroundJobs/BackgroundJobRepository.cs
- DVSAdmin.Data/Repositories/BackgroundJobs/IBackgroundJobRepository.cs
- DVSAdmin/DVSAdmin.csproj
- DVSAdmin/Program.cs
- DVSAdmin/Startup.cs
- DVSAdmin/appsettings.Development.json
- DVSAdmin/appsettings.json
Add Hangfire as a dependency to run a background jobs which sets the status of services with expired certificates to 'Removed'.
> Expired certificates background service

- DVSAdmin.Data/Repositories/RegisterManagement/RegManagementRepository.cs
- DVSAdmin.Data/Repositories/RemoveProvider/RemoveProviderRepository.cs
- DVSAdmin/Views/RegisterManagement/RegisterManagement.cshtml
- DVSAdmin/Views/RegisterManagement/ServiceRemovalConfirmation.cshtml
…verview if removed from register
> fix(admin) : fix how providers are ordered and remove services from overview

- DVSAdmin.BusinessLogic/Services/CsvDownload/CsvDownloadService.cs
- DVSAdmin.Data/Entities/Service.cs
- DVSAdmin.Data/Repositories/RegisterManagement/RegManagementRepository.cs
Adds a supplementary schemes column to the CSV download.
> Add supplementary schemes to Register CSV download.

- DVSAdmin.Data/Repositories/RegisterManagement/IRegManagementRepository.cs
- DVSAdmin.Data/Repositories/RegisterManagement/RegManagementRepository.cs
- DVSAdmin/Controllers/CertificateReviewController.cs
- DVSAdmin/Controllers/PublicInterestCheckController.cs
- DVSAdmin/Controllers/PublicInterestPrimaryCheckController.cs
- DVSAdmin/Controllers/PublicInterestSecondaryCheckController.cs
Add fix to allow certificate review for services with submitted status under provider with removed status
> Dvs 483 admin bug fixes

- DVSAdmin.BusinessLogic/Automapper/DaysLeftResolver.cs
- DVSAdmin/Views/RegisterManagement/ProviderDetails.cshtml
> Admin: Merge Dev to staging

- DVSAdmin.BusinessLogic/Services/RegManagement/RegManagementService.cs
- DVSAdmin.Data/Entities/TrustmarkNumber.cs
- DVSAdmin.Data/Repositories/RegisterManagement/RegManagementRepository.cs
> feat(re-application): remove old published version of the service when new version is published

- DVSAdmin/Views/RegisterManagement/PartialViews/_ProviderContactView.cshtml
Change title of 'basic information' to 'provider information' in the summary list component
> Summary list component - change Basic information to Provider information in h2 tag

- DVSAdmin/Views/Login/StartPage.cshtml
- DVSAdmin/Views/RegisterManagement/RegisterManagement.cshtml
fix(reg-management): change caps to lower in list
> fix(reg-management): change caps to lower in list

- DVSAdmin.Data/DVSAdminDbContext.cs
- DVSAdmin/Controllers/EditServiceController.cs
- DVSAdmin/Views/EditService/ServiceDifference.cshtml
> fix(edit-service): fixes in edit service , add EnableLegacyTimestampBehavior in db context

- DVSAdmin/Views/CertificateReview/CertificateReview.cshtml
- DVSAdmin/Views/CertificateReview/CertificateValidation.cshtml
- DVSAdmin/Views/CertificateReview/ConfirmApproval.cshtml
- DVSAdmin/Views/CertificateReview/ConfirmRejection.cshtml
- DVSAdmin/Views/CertificateReview/RejectSubmission.cshtml
- DVSAdmin/Views/PublicInterestPrimaryCheck/ConfirmPrimaryCheckFail.cshtml
- DVSAdmin/Views/PublicInterestPrimaryCheck/ConfirmPrimaryCheckPass.cshtml
- DVSAdmin/Views/PublicInterestPrimaryCheck/PrimaryCheckReview.cshtml
fix(reg-management): decapitalise v in validation on h1 heading
> fix(reg-management): decapitalise v in validation on h1 heading

- DVSAdmin/Views/PartialViews/_ServiceDetailsView.cshtml
- DVSAdmin/Views/PublicInterestSecondaryCheck/Approve/ConfirmSecondaryCheckApproval.cshtml
- DVSAdmin/Views/PublicInterestSecondaryCheck/Approve/ProceedSecondaryCheckApproval.cshtml
- DVSAdmin/Views/PublicInterestSecondaryCheck/Review/SecondaryCheckReview.cshtml
fix(reg-management): change content in public interest secondary checks
> fix(reg-management): change content in public interest secondary checks

- DVSAdmin.Data/DVSAdmin.Data.csproj
- DVSAdmin/DVSAdmin.csproj
> fix(security): update nuget packages

- DVSAdmin.BusinessLogic/Services/Edit/EditService.cs
- DVSAdmin/Controllers/EditServiceController.cs
- DVSAdmin/Views/EditService/ConformityExpiryDate.cshtml
- DVSAdmin/Views/EditService/ConformityIssueDate.cshtml
> Merge dev to staging

- DVSAdmin.BusinessLogic/ServiceHelper/ServiceHelper.cs.cs
- DVSAdmin.BusinessLogic/Services/Edit/EditService.cs
- DVSAdmin.Data/Repositories/RegisterManagement/RegManagementRepository.cs
This reverts commit 5909a5c81a8a9ee230f66a90e8521111d5d2113d.
> Revert "fix(edit-service): update the provider status when edits are requested"

- DVSAdmin/Views/CertificateReview/ConfirmRejection.cshtml
- DVSAdmin/Views/RemoveProvider/RemovalConfirmation.cshtml
fix(reg-management) change dsit to ofdia
> dvs-314-dvs-admin-content-update

- DVSAdmin/Views/PublicInterestPrimaryCheck/ConfirmPrimaryCheckFail.cshtml
fix(reg-management) remove first sentance in first paragraph
> fix(reg-management) remove first sentance in first paragraph

- DVSAdmin/Views/PublicInterestCheck/ArchiveDetails.cshtml
- DVSAdmin/Views/PublicInterestPrimaryCheck/ConfirmPrimaryCheckPass.cshtml
fix(reg-management): decapitalise o in open
> fix(reg-management): decapitalise o in open

- DVSAdmin/Views/PublicInterestPrimaryCheck/PrimaryCheckFailedConfirmation.cshtml
- DVSAdmin/Views/PublicInterestSecondaryCheck/Reject/ConfirmSecondaryCheckReject.cshtml
- DVSAdmin/Views/RegisterManagement/ProviderDetails.cshtml
- DVSAdmin/Views/RemoveProvider/ProceedRemoval.cshtml
fix(reg-management): decapitalise second words  in list
> fix(reg-management): decapitalise second words  in list

- DVSAdmin/Views/EditService/ServiceDifference.cshtml
- DVSAdmin/Views/PublicInterestPrimaryCheck/ConfirmPrimaryCheckFail.cshtml
- DVSAdmin/Views/PublicInterestPrimaryCheck/PrimaryCheckReview.cshtml
fix(reg-management): change dsit to ofdia
> fix(reg-management): change dsit to ofdia

- DVSAdmin/Views/PublicInterestPrimaryCheck/ConfirmPrimaryCheckFail.cshtml
- DVSAdmin/Views/PublicInterestSecondaryCheck/Review/SecondaryCheckReview.cshtml
- DVSAdmin/Views/RegisterManagement/ProviderDetails.cshtml
- DVSAdmin/Views/RemoveProvider/RemovalConfirmation.cshtml
- DVSAdmin/Views/RemoveProvider/ServiceRemovalConfirmation.cshtml
fix(reg-management): remove first sentence in first paragraph
> fix(reg-management): remove first sentence in first paragraph

- DVSAdmin/Models/Edit/EditService/ServiceSummaryViewModel.cs
> Admin : Prod deployment 12th March

- DVSAdmin.BusinessLogic/Services/RegManagement/RegManagementService.cs
- DVSAdmin.Data/Repositories/RemoveProvider/RemoveProviderRepository.cs
> fix(remove): clear remove column's data while updating status by priority

- DVSAdmin.BusinessLogic/Automapper/AutomapperProfile.cs
- DVSAdmin.BusinessLogic/Models/CABTransfer/CabTransferRequest.cs
- DVSAdmin.BusinessLogic/Models/CABTransfer/RequestManagement.cs
- DVSAdmin.BusinessLogic/Models/CertificateReview/CertificateReviewDto.cs
- DVSAdmin.BusinessLogic/Services/RegManagement/IRegManagementService.cs
- DVSAdmin.BusinessLogic/Services/RegManagement/RegManagementService.cs
- DVSAdmin.CommonUtility/Models/Enums/EventTypeEnum.cs
- DVSAdmin.CommonUtility/Models/Enums/RequestStatusEnum.cs
- DVSAdmin.CommonUtility/Models/Enums/RequestTypeEnum.cs
- DVSAdmin.Data/DVSAdminDbContext.cs
- DVSAdmin.Data/Entities/Cab.cs
- DVSAdmin.Data/Entities/CabTransferRequest.cs
- DVSAdmin.Data/Entities/CabUser.cs
- DVSAdmin.Data/Entities/RequestManagement.cs
- DVSAdmin.Data/Repositories/RegisterManagement/IRegManagementRepository.cs
- DVSAdmin.Data/Repositories/RegisterManagement/RegManagementRepository.cs
> feat(cab-reassign): save and cancel methods service and repository methods
